### ISSUE TITLE
Problem running Examples

### ISSUE THREAD

**Issue by jackbourkemckenna** [nathaniel-bennett/winsharpfuzz#1]
Hi,

I've discovered this project from looking into SharpFuzz and this project seems to be actively worked on. I've ran into a problem trying to follow the documentation but it appears I can't seem to get this run. When I run the following command: ` winsharpfuzz  --target_path="testingIdea/bin/Debug/netcoreapp3.1/testingIdea.exe" "testcases" -jobs=8` 
I get the following output: 
`Executing process...`
The application appear to crash/hangs - I'm not too sure what I've been doing wrong. I've been trying to follow your docs and get them to work with this example from [SharpFuzz](https://github.com/Metalnem/sharpfuzz#usage).  

Here are my project file if that helps: 

Program.cs 
```
using System;
using SharpFuzz;
using System.IO;

namespace Jil.testingIdea
{
    class Program
    {
        static void Main(string[] args)
        {
            Fuzzer.OutOfProcess.Run(stream => {

                try
                {
                    using (var reader = new StreamReader(stream))
                    {
                        JSON.DeserializeDynamic(reader);
                    }
                }
                catch (ArgumentException) { }
                catch (DeserializationException) { }

            });
        }
    }
}
```
csproj file - 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SharpFuzz" Version="1.6.2" />
		<PackageReference Include="WinSharpFuzz" Version="1.0.0" />

	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Jil">
	    <HintPath>..\..\sharpfuz\Jil.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>

```

Any assistance with this would be a great help - Thanks

**Comment by nathaniel-bennett** [comment]
Thanks for submitting the issue!

In this case, LibFuzzer appears to be working as intended--when you specify multiple jobs, it writes status output to various log files instead of the standard output (which is why it appears to be frozen--it never writes anything to the command line). In this case, you should have files such as `fuzz-0.log`, `fuzz-1.log` and so on show up in the directory that you ran the winsharpfuzz command from. These log files will be regularly updated with the status information you're looking for.

While this behavior is specific to LibFuzzer, I realize now that my documentation was a bit vague on that point. I'll update it to be more clear. Thanks for the feedback!

-Nathaniel

**Comment by jackbourkemckenna** [comment]
Thanks for replying to me, 

On your point about documentation being a bit vague maybe you could clear up some points for me as I'm still having some trouble getting this to run correctly. 

For Instrumenting a target library which in our case is a dll file - 

`winsharpfuzz-instrument \path\to\library.dll `

Then once we've written our test harness we start fuzzing  zing can be performed using one simple command:

winsharpfuzz --target_path="\path\to\HarnessExecutable.exe" "\path\to\corpus" [other-libfuzzer-options]

**Comment by jackbourkemckenna** [comment]
Thanks for replying to me, 

On your point about documentation being a bit vague maybe you could clear up some points for me as I'm still having some trouble getting this to run correctly. 

For Instrumenting a target library which in our case is a dll file - 

` winsharpfuzz-instrument Jil.dll`

 when I run the fuzzing command: 

`  winsharpfuzz  --target_path="testingIdea/bin/Debug/netcoreapp3.1/testingIdea.exe" "testcases"`

I see here in this command we are targeting a .exe file? is this correct as we instrumented a dll file in the step beforehand.

If I run that command I get the following error: 
```
WinSharpFuzz process exited.
Unhandled exception. System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at WinSharpFuzz.CommandLine.Program.<>c__DisplayClass1_0.<Main>b__0(Object sender, ConsoleCancelEventArgs a) in C:\Users\Nathaniel\Code\winsharpfuzz\src\WinSharpFuzz.CommandLine\Program.cs:line 84
   at System.Console.HandleBreakEvent(ConsoleSpecialKey controlKey)
   at System.ConsolePal.ControlCHandlerRegistrar.BreakEvent(Int32 controlType)
```

do you recommend any other examples to look at for a working example? as I'm fairly new to fuzzing myself. 

Thanks again

**Comment by nathaniel-bennett** [comment]
Yes--you first instrument the dll file (which basically inserts shims into that dll so that `winsharpfuzz` can detect when different code paths are executed). Then, you build the testing harness code with the instrumented dll file included as a dependency. Once that is built, you can run `winsharpfuzz` with the target path set to the testing harness executable (so `winsharpfuzz` targets the executable).

Hmmm... I haven't come across this particular error. Have you figured out what was causing it? I'd like to modify the command to give better output as to what's going wrong if possible
